name: E2E
on:
  push:
    branches:
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v3  

      - name: Create folder
        run: |
          mkdir -p cypress/screenshots

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots 
  
      - name: run cypress tests
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          browser: chrome
        env:
          THEME_ID: ${{ secrets.THEME_ID }}
